sensor:
  - platform: template
    name: ${property}
    id: ${property}
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    update_interval: ${interval}
    filters:
      - or:
        - throttle: ${interval}
        - delta: ${delta}
    lambda: |-
        queueRequest(${target}, Property::k${property});
        return {};
