defaults:
  interval: $interval_very_slow
  delta: "1.0"
  target: "Kessel"

sensor:
  - platform: template
    name: ${property}
    id: ${property}
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - or:
        - throttle: ${interval}
        - delta: ${delta}

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${property}),[](const SimpleVariant& value){
              using type = TypeMapping<Property::k${property}>::type;
              id(${property}).publish_state(value.get<type>());
          });
          queueRequest(${target}, Property::k${property});
