defaults:
  icon: "mdi:blank"
  accuracy_decimals: "0"
  target: "Kessel"

sensor:
  - platform: template
    name: ${property}
    id: ${property}
    icon: ${icon}
    accuracy_decimals: ${accuracy_decimals}

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${property}),[](const SimpleVariant& value){
              using type = TypeMapping<Property::k${property}>::type;
              id(${property}).publish_state(value.get<type>());
          });
          queueRequest(${target}, Property::k${property});
