esphome:
  platformio_options:
    build_flags:
      - "-DTHZ_504"

packages:
  BASE: !include { file: wp_base.yaml}

  HEIZGASTEMPERATUR:              !include { file: wp_temperature.yaml, vars: { property: "HEIZGASTEMPERATUR"       , disabled_by_default: "true" }} 
  VERFLUESSIGERTEMPERATUR:        !include { file: wp_temperature.yaml, vars: { property: "VERFLUESSIGERTEMPERATUR" , disabled_by_default: "true" }} 
  OELSUMPFTEMPERATUR:             !include { file: wp_temperature.yaml, vars: { property: "OELSUMPFTEMPERATUR"      , disabled_by_default: "true"}} 

  DRUCK_HEIZKREIS:                !include { file: wp_generic.yaml, vars: { property: "DRUCK_HEIZKREIS"          , interval: $interval_slow  , unit: "bar"  , icon: "mdi:gauge" , accuracy_decimals: "2" }}
  HOCHDRUCK:                      !include { file: wp_generic.yaml, vars: { property: "HOCHDRUCK"                , interval: $interval_slow  , unit: "bar"  , icon: "mdi:gauge" , disabled_by_default: "true" , accuracy_decimals: "2" }}
  DIFFERENZDRUCK:                 !include { file: wp_generic.yaml, vars: { property: "DIFFERENZDRUCK"           , interval: $interval_slow  , unit: "Pa"   , icon: "mdi:pump"  , disabled_by_default: "true" }}
  VERDICHTER_HEIZEN:              !include { file: wp_generic.yaml, vars: { property: "VERDICHTER_HEIZEN"        , interval: $interval_slow  , unit: "h"    , icon: "mdi:clock" }} 
  VERDICHTER_KUEHLEN:             !include { file: wp_generic.yaml, vars: { property: "VERDICHTER_KUEHLEN"       , interval: $interval_slow  , unit: "h"    , icon: "mdi:clock" }}
  VERDICHTER_WW:                  !include { file: wp_generic.yaml, vars: { property: "VERDICHTER_WW"            , interval: $interval_slow  , unit: "h"    , icon: "mdi:clock" }}
  EL_NE_HEIZEN:                   !include { file: wp_generic.yaml, vars: { property: "EL_NE_HEIZEN"             , interval: $interval_slow  , unit: "h"    , icon: "mdi:clock" }}
  EL_NE_WW:                       !include { file: wp_generic.yaml, vars: { property: "EL_NE_WW"                 , interval: $interval_slow  , unit: "h"    , icon: "mdi:clock" }}

